Services & Contacts Page
NIAEFEUP/website-ae pull request #20
Opened 2024-08-12 19:20 UTC by bellblex

Closes #5 & #8

2024-08-12 22:28 UTC, thePeras approved these changes
To be honest, "Send a message" forms text fields seems a little bit off. 
Also, I think "give your feedback" can be changed to "Give your anonymous feedback" 
I am approving, since not really important things for now

2024-08-13 14:17 UTC, rubuy-74 requested changes

2024-08-13 14:17 UTC, rubuy-74 commented on components/Contact/index.tsx
> +                  <label htmlFor="name">Full name</label>
These labels don't seem to be pointing at anything

2024-08-13 14:17 UTC, rubuy-74 commented on components/Info/index.tsx
> +const horariosData1 = [
The variables should be in English, for consistency

2024-08-13 14:17 UTC, rubuy-74 commented on components/Info/index.tsx
> +                    <strong>Email:</strong> <span><a href="mailto:aefeup@aefeup.pt">aefeup@aefeup.pt</a></span>
I think the styling should be done via CSS.

2024-08-29 18:26 UTC, rubuy-74 approved these changes
LGTM :rocket:

2024-08-29 18:27 UTC, merged