Pages/about
NIAEFEUP/website-ae pull request #29
Opened 2024-08-28 01:16 UTC by bellblex

Closes [#19]

2024-08-28 01:19 UTC, bellblex commented
I didn't linked to payload yet

2024-08-29 01:23 UTC, rubuy-74 requested changes
Looks great, but I think the departments boxes could have more padding.

![image](https://github.com/user-attachments/assets/2a7d8989-803c-4a7e-ba7e-849f66a5a761)

2024-08-29 01:38 UTC, rubuy-74 requested changes
It looks very nice, but I just have some small comments.

2024-08-29 01:38 UTC, rubuy-74 commented on app/(site)/about/MenuDescription.tsx
> +      <h3 className="text-3xl font-medium text-black dark:text-white">Departamentos</h3>
Shouldn't this be a SectionHeader?

2024-08-29 01:38 UTC, rubuy-74 commented on app/(site)/about/MenuDescription.tsx
> +          <div className="flex flex-col gap-4 w-1/4">
I think this would look better if it were centered based off of the cards on the right.

2024-08-29 01:38 UTC, rubuy-74 commented on app/(site)/about/page.tsx
> +        <SectionHeader
This could be in the AvatarLineup Component, because is directly associated with it.

2024-08-29 01:38 UTC, rubuy-74 commented on app/(site)/sport/teams/LineupsSlider.tsx
> +"use client";
This file is from a different issue.

2024-09-15 02:11 UTC, rubuy-74 approved these changes

2024-09-30 14:08 UTC, merged